import React from 'react'

export default function brahma() {
    return (
        <div>brahma</div>
    )
}
// Think of your problem...
// Ask Brahma a No.bet'n 1 - 720...
// a Number comes to your mind...
// That Number = Brahma Answer...